env:
  global:
    - CC_TEST_REPORTER_ID=24fc7132647f84f0693294c596994d8f7283b78c3309658978af852587b66400

language: python
python: 3.6.10

before_install:
  - pip install poetry

install:
  - make install

script:
  - make lint
  - make pytest
  - make coverage
