name: hexlet-check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.10
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.0.3
      - name: Install flake8
        run: pip install flake8
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run flake8 linter
        run: make lint
