name: hexlet-check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run flake8 linter
        run: make lint
