name: tests-status

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.12
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.0.3
      - name: Install pytest
        run: pip install pytest
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run pytest
        run: make pytest
